### ISSUE TITLE
rename "digest_index" as "fragment_index"

### ISSUE THREAD

**Issue by paulhuggett** [SNSystems/pstore#2]
This applies to both database::get_digest_index() and pstore::index::digest_index. It maps from digests to fragments; using the value type seems more logical and consistent with pstore::index::ticket_index.

**Comment by paulhuggett** [comment]
(Bear in mind that this is a breaking API change so check with the https://github.com/SNSystems/llvm-prepo before committing!)

**Comment by MaggieYingYi** [comment]
Fixed in llvm-prepo: commit 1b147b734a797b2db8c1612b6546a81ac0f17765 and pstore commit b729f0ceb3c54ad7d018808c8b189f695bceb2db.
